import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "SIMPLE SHOPPING APP",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={`antialiased`}>{children}</body>
        </html>
    );
}
