import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

import { CartProvider } from "@/context/CartContext";

export const metadata: Metadata = {
    title: "TO DO APP",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={`antialiased`}>
                <CartProvider>
                    <Header />
                    {children}
                </CartProvider>
            </body>
        </html>
    );
}
